---
title: "Brownian Bridge"
format:
  html: default
  pdf:
    mainfont: "Times New Roman"
    lang: en
---


In the most common formulation, the Brownian bridge process is obtained by taking a standard Brownian motion process $X$, restricted to the interval $[0,1]$, and conditioning on the event that $X_1 = 0$. Since also $X_0 = 0$, the process is tied down at both ends, and so the process in between forms a bridge. The Brownian bridge turns out to be an interesting stochastic process with surprising applications, including a very important application to statistics.

The expected value of the bridge is zero, with variance $\frac{t(T-t)}{T}$, implying that the most uncertainty is in the middle of the bridge, with zero uncertainty at the nodes. The increments in a Brownian bridge are not independent.

A Brownian bridge is the result of Donsker's theorem (a functional extension of the CLT) in the area of empirical processes. It is also used in the Kolmogorov–Smirnov test in the area of statistical inference.

---

## Definition

A Brownian bridge is a stochastic process $X = \{X_t: t \in [0,1]\}$ with state space $\mathbb{R}$ that satisfies the following properties:

- $X_0 = 0$ and $X_1 = 0$ w.p.1  
- $X$ is a Gaussian process  
- $E(X_t) = 0$ for $t \in [0,1]$  
- $\text{cov}(X_s, X_t) = \min\{s,t\} - st$ for $s,t \in [0,1]$  
- w.p.1 $t \mapsto X_t$ is continuous on $[0,1]$  

## Properties

1. If $B(t)$ is a BM and $A$ is any positive number, then $\tilde{B}(t) = A^{1/2} B(t/A)$ is also a BM.  
2. If $B(t)$ is a BM, then $\tilde{B}^\circ(u) = B(u) - u B(1), u \in [0,1]$, is a BB.  
3. If $\{B^\circ(u)\}$ is a BB, then $\tilde{B}(t) = (t + 1) B^\circ(t/(t + 1))$ is a BM.  
4. If $\{B(t)\}$ is a BM and $T$ is a fixed positive number, then $\tilde{B}(t) = B(T + t) - B(T)$ is also a BM and independent of $\{B(s), s \in [0,T]\}$.

## Applications

1. Brownian bridge appears as a limit of empirical distributions.  
2. It can reduce simulation paths, improving computational efficiency when dealing with many underlying factors.  
3. In path-dependent derivative pricing (e.g., barrier options), Brownian bridge helps estimate "knock-out" probabilities with reduced granularity.

## References

- [Donsker’s Theorem — MIT OCW](https://ocw.mit.edu/courses/mathematics/18-650-statistics-for-applications-fall-2016/lecture-slides/MIT18_650F16_Testing_GF.pdf)  
- [Lecture PDF on Applications](https://dspace.mit.edu/bitstream/handle/1721.1/37302/18-175Spring-2005/NR/rdonlyres/1974B061-49AB-4653-9696-1F5CDB1B690D/0/lecture29.pdf)