name: Deploy Quarto Site

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://yihui.org/tinytex/install-bin-unix.sh | sh
          echo "export PATH=$HOME/bin:\$PATH" >> $GITHUB_ENV

      - name: Render HTML and PDF
        run: |
          quarto render --to html
          quarto render --to pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site