name: Deploy Quarto Site

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2

      # 🆕 Установка TeXLive через apt
      - name: Install TeXLive (basic + fonts)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-xetex texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra

      - name: Render HTML and PDF
        run: |
          quarto render --to html
          quarto render --to pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site